# Path to your oh-my-zsh installation.
export ZSH="/home/$USER/.oh-my-zsh"

# General Settings
ZSH_THEME="dallas"
COMPLETION_WAITING_DOTS="true"
plugins=(zsh-syntax-highlighting git zsh-autosuggestions history-substring-search)

# User configuration
git config --global pager.branch false
# alias git_RESET_FORK="git remote add upstream /url/to/original/repo && git fetch upstream &&git checkout master &&git reset --hard upstream/master && git push origin master --force "
alias git_RESET="git reset --hard origin/master && git pull origin master"
alias docker="podman"
alias clear="tput reset"
alias volume="pavucontrol"
alias files="nautilus"
export TRASH="$HOME/.local/share/Trash/files" 

# Imports
source $ZSH/oh-my-zsh.sh
source ~/.profile

# Shell Prompt
eval "$(starship init zsh)"
